### ISSUE TITLE
api 호출

### ISSUE THREAD

**Issue by sydney-choi** [f-lab-edu/vanilla-toss-tech#4]
article을 클릭할 때마다 api가 한 개씩 증가하여 호출되는 문제
<img width="400" alt="스크린샷 2024-02-14 01 53 06" src="https://github.com/f-lab-edu/vanilla-toss-tech/assets/68490447/f1f3f704-5255-4bb3-a3fd-7f1c9b33f9aa">

**Comment by f-lab-ash** [comment]
cleanup에 관련해서 찾아보시고 어떤 부분이 문제일지 생각해주세요!

**Comment by sydney-choi** [comment]
fixed issue
